<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRi9da0n\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRi9da0n/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRi9da0n.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRi9da0n\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRi9da0n\appProdProjectContainer([
    'container.build_hash' => 'Ri9da0n',
    'container.build_id' => '80c5995e',
    'container.build_time' => 1646793917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRi9da0n');
